[tool.poetry]
name = "anymusicbot"
version = "0.1.0"
description = ""
authors = ["BarsTiger"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.1.1"
rich = "^13.6.0"
py-deezer = "^1.1.4.post1"
soundcloud-lib = "^0.6.1"
shazamio = { path = "lib/ShazamIO" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
